##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#  mybatis.mapper-locations=classpath:mappers/*xml
#  #指定Mybatis的实体目录
#  mybatis.type-aliases-package=com.itheima.mybatis.entity
#  # 应用服务 WEB 访问端口
#  server.port=8080
spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.199.171:3306/courseselectionsystem
    username: sqlUser
    password: strong_password
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#spring事务管理日志
logging:

  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug